apiVersion: apps/v1
kind: Deployment
metadata:
  name: tls-issue-tester-go1.16.7-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tls-issue-tester
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9121"
        prometheus.io/scheme: "https"
      labels:
        app: tls-issue-tester
    spec:
      containers:
      - name: redis
        image: redis:6.2
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /tls-data
          name: tls-volume
        command: ["redis-server"]
        args: ["--tls-port", "6379", "--port", "0", "--tls-cert-file", "/tls-data/redis.crt", "--tls-key-file", "/tls-data/redis.key", "--tls-ca-cert-file", "/tls-data/ca.crt", "--loglevel", "debug"]

      - name: redis-tls-updater
        image: redis-tls-updater:0.1.0
        volumeMounts:
        - mountPath: /tls-data
          name: tls-volume
        env:
        - name: WATCH_FILES
          value: '/tls-data/redis.crt:/tls-data/redis.key'
        - name: REDIS_TLS_CLIENT_CERT_FILE
          value: '/tls-data/exporter-c.crt'
        - name: REDIS_TLS_CLIENT_KEY_FILE
          value: '/tls-data/exporter-c.key'
        - name: REDIS_TLS_CA_CERT_FILE
          value: '/tls-data/ca.crt'
        - name: REDIS_URI
          value: 'rediss://localhost:6379'

      - name: tls-tester
        image: bjosv/tls-issue-tester:1.16.7-3
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: /tls-data
          name: tls-volume

      volumes:
      - name: tls-volume
        hostPath:
          # directory location on host
          path: /tls-data
