global:
  scrape_interval:     5s # By default, scrape targets every 15 seconds.
  evaluation_interval: 5s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'prometheus'

    # Override the global default
    # scrape_interval: 120s

    static_configs:
         - targets: ['cadvisor:8080']
